### ISSUE TITLE
Can't connect to Redis

### ISSUE THREAD

**Issue by reebderdieb** [mhzawadi/foxess-mqtt#36]
Running in a docker Container. Redis is pingable by IP and container name through container console, but foxess-mqtt brings:

PHP Fatal error:  Uncaught RedisException: php_network_getaddresses: getaddrinfo for  failed: Name does not resolve in /foxess-mqtt/src/model/mhredis.php:25
PHP Warning:  Redis::connect(): php_network_getaddresses: getaddrinfo for  failed: Name does not resolve in /foxess-mqtt/src/model/mhredis.php on line 25

**Comment by mhzawadi** [comment]
Hello 👋🏼 

In your config the host name of redis should match the name in docker, as docker will do the dns.

could you paste your compose to see what you have?

**Comment by reebderdieb** [comment]
I don't use a compose file, I use Portainer, however my Redis container is called Redis and from inside of the FoxESS-MQTT containers console I can ping by using: ping Redis. I then get the correct IP, so it seems to be reachable. When configuring Redis without any security, so with the port opened to any connection. The redis logs show some information about connections, e.g when pointing the browser to the redis IP and port. However nothing happens through FoxESS-MQTT.

**Comment by mhzawadi** [comment]
ok, that is odd. I know you can start containers that way, but I've not used it.

Could you import the below compose file and see if that works?

1. click `App Templates`
2. then `Custom Templates`
3. then the blue button `Add Custom Template`
4. fill in the name and Description
5. paste the blow code in to the `Wed Editor` box
  1. you may want to edit the the `foxess_data` volume to where you have config
6. click the blue `Create custom template` at the bottom

```
version: "2.1"

volumes:
  redis_data:
  foxess_data:

services:
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

  foxess-mqtt:
    image: mhzawadi/foxess-mqtt:latest
    container_name: foxess-mqtt
    restart: unless-stopped
    volumes:
      - foxess_data:/foxess-mqtt/data
    environment:
      - TIMEZONE=Europe/London
```
