### ISSUE TITLE
config.json overwritten on start

### ISSUE THREAD

**Issue by normanu** [mhzawadi/foxess-mqtt#61]
I made the config.json but every time I start or restart the container it overwrites the config.json.
I use the docker compose settings.

**Comment by mhzawadi** [comment]
Hello,

Could you please port your compose file?

**Comment by normanu** [comment]
Compose file is,

volumes:
  redis_data:

services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis_data:/data

  foxess-mqtt:
    image: mhzawadi/foxess-mqtt
    container_name: foxess-mqtt
    volumes:
      - ./config.json:/foxess-mqtt/data/config.json
    environment:
      - TIMEZONE=Europe/Amsterdam


Op wo 9 apr 2025 om 09:48 schreef Matthew Horwood ***@***.***

**Comment by mhzawadi** [comment]
I think the issue is that the `/foxess-mqtt/data` directory is a volume, so your load the config fails.

Could you edit the compose to use a directory?

```
volumes:
  redis_data:

services:
  redis:
    image: redis
    container_name: redis
    volumes:
      - redis_data:/data

  foxess-mqtt:
    image: mhzawadi/foxess-mqtt
    container_name: foxess-mqtt
    volumes:
      - ./data:/foxess-mqtt/data
    environment:
      - TIMEZONE=Europe/Amsterdam
```
